---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build:
    executor: docker/docker
    steps:
      - checkout
      - docker/install-docker-compose
      - run:
          name: Build Spark
          command: docker-compose run spark-executor-builder /build.sh
      - store_artifacts:
          path: dist

workflows:
  build:
    jobs:
      - build
