---
version: 2.1

orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-spark:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Spark
          command: docker-compose run spark-executor-builder /build-spark.sh
      - store_artifacts:
          path: dist

workflows:
  build:
    jobs:
      - build-spark
